/* =====================================================================
   JDA Admin Panel — reports.js   (reports.html)
   Service-wise status report for the zone of the selected charge.
   ===================================================================== */

(function (window, document) {
  "use strict";

  if (!window.AdminLayout.ready) return;

  const { AdminData, AdminForm, AdminToast, AdminUtil } = window;
  const { escapeHtml } = AdminUtil;
  const { Session, ApplicationStore, STATUS, daysFromToday } = AdminData;

  const $ = id => document.getElementById(id);
  const charge = Session.getCharge();
  const COLS = [
    ["Total",                a => true],
    ["Pending",              a => a.status === STATUS.PENDING],
    ["On Hold",              a => a.status === STATUS.HOLD],
    ["Pending At Applicant", a => a.status === STATUS.APPLICANT],
    ["Other Department",     a => a.status === STATUS.OTHER],
    ["Disposed",             a => a.status === STATUS.DISPOSED],
    ["Due Expired",          a => a.status !== STATUS.DISPOSED && daysFromToday(a.dueDate) < 0]
  ];
  let table = [];

  /* BACKEND INTEGRATION: replace with the report API (zone + filters). */
  function build() {
    const from = $("rFrom").value, to = $("rTo").value;
    const svc = $("rService").value, st = $("rStatus").value;
    const apps = ApplicationStore.byZone(charge.zoneId).filter(a => {
      const d = a.startDate.slice(0, 10);
      return (!from || d >= from) && (!to || d <= to) && (!svc || a.service.name === svc) && (!st || a.status === st);
    });
    const services = [...new Set(apps.map(a => a.service.name))].sort();
    table = services.map(s => [s, ...COLS.map(([, fn]) => apps.filter(a => a.service.name === s && fn(a)).length)]);
    return apps.length;
  }

  function render() {
    const total = build();
    $("reportEmpty").hidden = total > 0;
    $("reportTable").closest(".admin-table-wrap").hidden = total === 0;
    $("reportBody").innerHTML = table.map(r => `<tr><td>${escapeHtml(r[0])}</td>${r.slice(1).map(n => `<td class="admin-col-amount">${n}</td>`).join("")}</tr>`).join("");
    const sums = COLS.map((_, i) => table.reduce((s, r) => s + r[i + 1], 0));
    $("reportFoot").innerHTML = `<tr><th scope="row">Total</th>${sums.map(n => `<td class="admin-col-amount"><strong>${n}</strong></td>`).join("")}</tr>`;
    $("reportMeta").textContent = `${total} application${total === 1 ? "" : "s"} · generated ${AdminUtil.formatDateTime(AdminData.nowIso())}`;
  }

  function exportCsv() {
    const q = v => `"${String(v).replace(/"/g, '""')}"`;
    const lines = [["Service Name", ...COLS.map(c => c[0])].map(q).join(",")]
      .concat(table.map(r => r.map(q).join(",")));
    const blob = new Blob(["﻿" + lines.join("\r\n")], { type: "text/csv;charset=utf-8" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = `jda-service-report-${charge.zone}.csv`;
    document.body.appendChild(a);
    a.click();
    setTimeout(() => { URL.revokeObjectURL(a.href); a.remove(); }, 0);
  }

  $("reportSubtitle").textContent = `Service-wise application status report for ${charge.department} (${charge.zone}).`;
  const services = [...new Set(ApplicationStore.byZone(charge.zoneId).map(a => a.service.name))].sort();
  $("rService").insertAdjacentHTML("beforeend", services.map(s => `<option>${escapeHtml(s)}</option>`).join(""));
  $("rStatus").insertAdjacentHTML("beforeend", Object.values(STATUS).map(s => `<option>${escapeHtml(s)}</option>`).join(""));
  AdminForm.liveClear($("reportFilters"));

  $("reportFilters").addEventListener("submit", e => {
    e.preventDefault();
    AdminForm.clearAll(e.target);
    if ($("rFrom").value && $("rTo").value && $("rTo").value < $("rFrom").value) {
      AdminForm.setError($("rTo"), "To Date cannot be before From Date.");
      $("rTo").focus();
      return;
    }
    render();
  });
  $("rReset").addEventListener("click", () => { $("reportFilters").reset(); AdminForm.clearAll($("reportFilters")); render(); });
  $("exportCsv").addEventListener("click", exportCsv);
  $("exportExcel").addEventListener("click", () =>
    AdminToast.show("Excel files will be generated by the server. Use Export CSV in this prototype.", "info", "Export Excel"));
  $("printReport").addEventListener("click", () => window.print());

  render();
})(window, document);
