/* =====================================================================
   JDA Admin Panel — reports.js   (reports.html)
   Service-wise status report for the zone of the selected charge.
   ===================================================================== */

(function (window, document, $) {
  "use strict";

  if (!window.AdminLayout.ready) return;

  const { AdminData, AdminForm, AdminToast, AdminUtil } = window;
  const { escapeHtml } = AdminUtil;
  const { Session, ApplicationStore, STATUS, daysFromToday } = AdminData;

  const charge = Session.getCharge();
  const $filters = $("#reportFilters");
  const COLS = [
    ["Total",                a => true],
    ["Pending",              a => a.status === STATUS.PENDING],
    ["On Hold",              a => a.status === STATUS.HOLD],
    ["Pending At Applicant", a => a.status === STATUS.APPLICANT],
    ["Other Department",     a => a.status === STATUS.OTHER],
    ["Disposed",             a => a.status === STATUS.DISPOSED],
    ["Due Expired",          a => a.status !== STATUS.DISPOSED && daysFromToday(a.dueDate) < 0]
  ];
  let table = [];

  /* BACKEND INTEGRATION: replace with the report API (zone + filters). */
  function build() {
    const from = $("#rFrom").val(), to = $("#rTo").val();
    const svc = $("#rService").val(), st = $("#rStatus").val();
    const apps = ApplicationStore.byZone(charge.zoneId).filter(a => {
      const d = a.startDate.slice(0, 10);
      return (!from || d >= from) && (!to || d <= to) && (!svc || a.service.name === svc) && (!st || a.status === st);
    });
    const services = [...new Set(apps.map(a => a.service.name))].sort();
    table = services.map(s => [s, ...COLS.map(([, fn]) => apps.filter(a => a.service.name === s && fn(a)).length)]);
    return apps.length;
  }

  function render() {
    const total = build();
    $("#reportEmpty").prop("hidden", total > 0);
    $("#reportTable").closest(".admin-table-wrap").prop("hidden", total === 0);
    $("#reportBody").html(table.map(r => `<tr><td>${escapeHtml(r[0])}</td>${r.slice(1).map(n => `<td class="admin-col-amount">${n}</td>`).join("")}</tr>`).join(""));
    const sums = COLS.map((_, i) => table.reduce((s, r) => s + r[i + 1], 0));
    $("#reportFoot").html(`<tr><th scope="row">Total</th>${sums.map(n => `<td class="admin-col-amount"><strong>${n}</strong></td>`).join("")}</tr>`);
    $("#reportMeta").text(`${total} application${total === 1 ? "" : "s"} · generated ${AdminUtil.formatDateTime(AdminData.nowIso())}`);
  }

  function exportCsv() {
    const q = v => `"${String(v).replace(/"/g, '""')}"`;
    const lines = [["Service Name", ...COLS.map(c => c[0])].map(q).join(",")]
      .concat(table.map(r => r.map(q).join(",")));
    const blob = new Blob(["﻿" + lines.join("\r\n")], { type: "text/csv;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const $a = $("<a>").attr({ href: url, download: `jda-service-report-${charge.zone}.csv` }).appendTo("body");
    $a[0].click();
    setTimeout(() => { URL.revokeObjectURL(url); $a.remove(); }, 0);
  }

  $("#reportSubtitle").text(`Service-wise application status report for ${charge.department} (${charge.zone}).`);
  const services = [...new Set(ApplicationStore.byZone(charge.zoneId).map(a => a.service.name))].sort();
  $("#rService").append(services.map(s => `<option>${escapeHtml(s)}</option>`).join(""));
  $("#rStatus").append(Object.values(STATUS).map(s => `<option>${escapeHtml(s)}</option>`).join(""));
  AdminForm.liveClear($filters);

  $filters.on("submit", function (e) {
    e.preventDefault();
    AdminForm.clearAll($filters);
    const from = $("#rFrom").val(), to = $("#rTo").val();
    if (from && to && to < from) {
      AdminForm.setError("#rTo", "To Date cannot be before From Date.");
      $("#rTo").trigger("focus");
      return;
    }
    render();
  });
  $("#rReset").on("click", function () { $filters[0].reset(); AdminForm.clearAll($filters); render(); });
  $("#exportCsv").on("click", exportCsv);
  $("#exportExcel").on("click", () =>
    AdminToast.show("Excel files will be generated by the server. Use Export CSV in this prototype.", "info", "Export Excel"));
  $("#printReport").on("click", () => window.print());

  render();
})(window, document, jQuery);
